"""Metric computation surface: extent, persistence, dynamics, connectivity, patches."""

from hydrofragments.metrics.clustering import (
    InterPoolGapResult,
    compute_inter_pool_gaps,
)
from hydrofragments.metrics.connectivity import (
    FixedGraph,
    RealisedConnectivityResult,
    TcfResult,
    build_fixed_graph,
    compute_length_weighted_rc_pair,
    compute_realised_connectivity,
    compute_tcf,
)
from hydrofragments.metrics.dynamics import (
    DualCompositeUnavailableError,
    ExtentContractionResult,
    ReconnectionTimingResult,
    RefugeSpatialStabilityResult,
    compute_extent_contraction,
    compute_reconnection_timing,
    compute_refuge_spatial_stability,
)
from hydrofragments.metrics.extent import (
    ApsecRecord,
    LpsecResult,
    compute_apsec,
    compute_lpsec,
)
from hydrofragments.metrics.patches import (
    MeshCorrelationGate,
    PatchMetricResult,
    PoolWidthDistribution,
    analyze_patch_metrics,
    analyze_pool_width_distribution,
    compute_patch_metrics,
    compute_pool_width_distribution,
    evaluate_mesh_correlation_gate,
)
from hydrofragments.metrics.persistence import (
    HydroperiodResult,
    OccurrenceResult,
    RecurrenceResult,
    RefugeAreaResult,
    compute_hydroperiod,
    compute_occurrence,
    compute_recurrence,
    compute_refuge_area,
)
from hydrofragments.metrics.registry import (
    METRIC_REGISTRY,
    PROFILES,
    MetricPlan,
    MetricSkip,
    MetricSpec,
    RegistryError,
    resolve_metrics,
)

__all__ = [
    "ApsecRecord",
    "DualCompositeUnavailableError",
    "ExtentContractionResult",
    "FixedGraph",
    "HydroperiodResult",
    "InterPoolGapResult",
    "LpsecResult",
    "METRIC_REGISTRY",
    "MeshCorrelationGate",
    "MetricPlan",
    "MetricSkip",
    "MetricSpec",
    "OccurrenceResult",
    "PROFILES",
    "PatchMetricResult",
    "PoolWidthDistribution",
    "RealisedConnectivityResult",
    "ReconnectionTimingResult",
    "RecurrenceResult",
    "RefugeAreaResult",
    "RefugeSpatialStabilityResult",
    "RegistryError",
    "TcfResult",
    "analyze_patch_metrics",
    "analyze_pool_width_distribution",
    "build_fixed_graph",
    "compute_apsec",
    "compute_extent_contraction",
    "compute_hydroperiod",
    "compute_inter_pool_gaps",
    "compute_length_weighted_rc_pair",
    "compute_lpsec",
    "compute_occurrence",
    "compute_patch_metrics",
    "compute_pool_width_distribution",
    "compute_realised_connectivity",
    "compute_reconnection_timing",
    "compute_recurrence",
    "compute_refuge_area",
    "compute_refuge_spatial_stability",
    "compute_tcf",
    "evaluate_mesh_correlation_gate",
    "resolve_metrics",
]
